version: 2
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 9 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - run
jobs:
 run:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t evolve/ert:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker run --rm evolve/ert:$CIRCLE_BRANCH
