version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t evolve/ert:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker run --rm -e SLACK_WEBHOOK=${SLACK_WEBHOOK} evolve/ert:$CIRCLE_BRANCH 
