version: 2
jobs:
 run:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t evolve/ert:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker run --rm evolve/ert:$CIRCLE_BRANCH
